substitutions:
  name: basen-bms-ble
  device_description: "Monitor a Basen Battery Management System via BLE"
  external_components_source: github://syssi/esphome-basen-bms@main
  mac_address: A4:C1:38:27:48:9A

esphome:
  name: ${name}
  friendly_name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-basen-bms"
    version: 1.4.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${mac_address}
    id: client0

basen_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 10s

binary_sensor:
  - platform: basen_bms_ble
    balancing:
      name: "balancing"
    charging:
      name: "charging"
    discharging:
      name: "discharging"

sensor:
  - platform: basen_bms_ble
    total_voltage:
      name: "total voltage"
    current:
      name: "current"
    power:
      name: "power"
    charging_power:
      name: "charging power"
    discharging_power:
      name: "discharging power"
    capacity_remaining:
      name: "capacity remaining"
    charging_states_bitmask:
      name: "charging states bitmask"
    discharging_states_bitmask:
      name: "discharging states bitmask"
    charging_warnings_bitmask:
      name: "charging warnings bitmask"
    discharging_warnings_bitmask:
      name: "discharging warnings bitmask"
    balancing_cells_bitmask:
      name: "balancing cells bitmask"
    state_of_charge:
      name: "state of charge"
    nominal_capacity:
      name: "nominal capacity"
    nominal_voltage:
      name: "nominal voltage"
    real_capacity:
      name: "real capacity"
    serial_number:
      name: "serial number"
    charging_cycles:
      name: "charging cycles"
    min_cell_voltage:
      name: "min cell voltage"
    max_cell_voltage:
      name: "max cell voltage"
    min_voltage_cell:
      name: "min voltage cell"
    max_voltage_cell:
      name: "max voltage cell"
    delta_cell_voltage:
      name: "delta cell voltage"
    average_cell_voltage:
      name: "average cell voltage"
    temperature_1:
      name: "temperature 1"
    temperature_2:
      name: "temperature 2"
    temperature_3:
      name: "temperature 3"
    temperature_4:
      name: "temperature 4"
    cell_voltage_1:
      name: "cell voltage 1"
    cell_voltage_2:
      name: "cell voltage 2"
    cell_voltage_3:
      name: "cell voltage 3"
    cell_voltage_4:
      name: "cell voltage 4"
    cell_voltage_5:
      name: "cell voltage 5"
    cell_voltage_6:
      name: "cell voltage 6"
    cell_voltage_7:
      name: "cell voltage 7"
    cell_voltage_8:
      name: "cell voltage 8"
    cell_voltage_9:
      name: "cell voltage 9"
    cell_voltage_10:
      name: "cell voltage 10"
    cell_voltage_11:
      name: "cell voltage 11"
    cell_voltage_12:
      name: "cell voltage 12"
    cell_voltage_13:
      name: "cell voltage 13"
    cell_voltage_14:
      name: "cell voltage 14"
    cell_voltage_15:
      name: "cell voltage 15"
    cell_voltage_16:
      name: "cell voltage 16"
    cell_voltage_17:
      name: "cell voltage 17"
    cell_voltage_18:
      name: "cell voltage 18"
    cell_voltage_19:
      name: "cell voltage 19"
    cell_voltage_20:
      name: "cell voltage 20"
    cell_voltage_21:
      name: "cell voltage 21"
    cell_voltage_22:
      name: "cell voltage 22"
    cell_voltage_23:
      name: "cell voltage 23"
    cell_voltage_24:
      name: "cell voltage 24"

switch:
  - platform: basen_bms_ble
    charging:
      name: "charging"
    discharging:
      name: "discharging"

  - platform: ble_client
    ble_client_id: client0
    name: "enable bluetooth connection"
    id: ble_client_switch0

text_sensor:
  - platform: basen_bms_ble
    charging_states:
      name: "charging states"
    discharging_states:
      name: "discharging states"
    charging_warnings:
      name: "charging warnings"
    discharging_warnings:
      name: "discharging warnings"
    manufacturing_date:
      name: "manufacturing date"
    balancing_cells:
      name: "balancing cells"
